### ISSUE TITLE
Code examples incorrectly states to import the object 'dintero'

### ISSUE THREAD

**Issue by svenrog** [Dintero/Dintero.Checkout.Web.SDK#25]
Code examples in readme states to import `{ dintero }`
While actual module exports are `{ embed, redirect }`

**Comment by svnv** [comment]
Hi @svenrog thanks for reporting this!

 In addition to the wrong examples in the README.md I found that there was a bug (well several) actually in the build tool we used so we ended up changing a bit of our tooling. The typescript types in the bundle should work "out of the box" now as well when imported into a typescript project.
