### ISSUE TITLE
Vipps error

### ISSUE THREAD

**Issue by edas11** [Dintero/Dintero.Checkout.Web.SDK#390]
When I try to pay using Vipps on mobile I get this error (urls are changed here):
 
`Unsafe attempt to initiate navigation for frame with origin 'https://www.website.com' from frame with URL 'https://apitest.vipps.no/dwo-api-application/v1/deeplink/vippsgateway'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.`

After I get this message the button `Next` doesn't work anymore and I'm unable to finish paying with Vipps.

![image](https://github.com/user-attachments/assets/26c49d94-914d-4b59-b996-a68fffefed64)

This happens only on mobile. On desktop it works fine. Can you look into it? Looks like `iframe` `sandbox` attribute needs more values. Or Vipps needs to do no redirects.

**Comment by svnv** [comment]
Hi, @edas11   thanks for reporting this issue. Are you using an iPhone or Android or both? What browser are you using?

**Comment by edas11** [comment]
I got this error on Android Chrome and on Ubuntu Chromium when testing mobile screen size in dev tools.

**Comment by svnv** [comment]
@edas11 should be fixed in new version 0.8.9
